### ISSUE TITLE
Add Article - Org Roam

### ISSUE THREAD

**Issue by TheCatster** [SystemCrafters/wiki-site#5]
Org Roam is an amazing tool that is highly customisable. Including information about it in the Emacs wiki would be great!

**Comment by benoitj** [comment]
Any ideas what we would want in it?
like:
- general description of org-roam
- what it adds over org-mode
- links to the main org-roam site
- hints
-- file naming
-- capture templates
-- why sometimes you cant find your roam file

**Comment by benoitj** [comment]
+ useful commands

I think the idea is to point people in the right direction, not to reproduce the org-roam guide

**Comment by TheCatster** [comment]
I believe that a very quick (one paragraph or so) general description would be appropriate, links of course to the project, hints, and various guides. Think more the community aspect of knowledge, not, as you correctly say, reproduce existing wikis or guides.

**Comment by benoitj** [comment]
do we think this is now closed by the latest PR?

**Comment by TheCatster** [comment]
Yes, absolutely,
